server:
  port: 9009

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: http://116.236.234.246:10182/cmsxc/cmsxc-config.git
          username: cms_config
          password: cms_config
          search-paths: /uat
